### ISSUE TITLE
SubMenu list hidden by Menu items

### ISSUE THREAD

**Issue by Philippe-Collignon** [codetok/cdk-admin#10]
Hello,

![43006868-6a76aaf4-8c54-11e8-80f8-bd715016b8c3](https://user-images.githubusercontent.com/7871716/43213976-381780c8-9038-11e8-93d1-67d9e8513fe8.png)

Sub-menus are hidden by menus.

Chrome on Linux but it is not a browser issue as your firebase app is working perfectly.
Maybe Angular version ?
Thanks for nice Theme.

ng -v  

Angular CLI: 6.0.8
Node: 8.10.0
OS: linux x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.3.3
@angular/cli                      6.0.8
@angular/flex-layout              5.0.0-beta.14
@angular/material                 6.3.3
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

**Comment by harikrishna266** [comment]
hey @Philippe-Collignon can you pull the code and check if the issue is fixed
