### ISSUE TITLE
Cannot find module 'firebase/app'

### ISSUE THREAD

**Issue by hooh88** [codetok/cdk-admin#15]
Hi
After run `ng serve` the error below is displayed : 

ERROR in node_modules/angularfire2/auth/auth.d.ts(1,27): error TS2307: Cannot find module 'firebase/app'.
node_modules/angularfire2/database/database.d.ts(1,26): error TS2307: Cannot find module 'firebase/app'.
node_modules/angularfire2/database/interfaces.d.ts(1,27): error TS2307: Cannot find module 'firebase/app'.
node_modules/angularfire2/database/list/audit-trail.d.ts(3,26): error TS2307: Cannot find module 'firebase/app'.
node_modules/angularfire2/database/list/state-changes.d.ts(3,26): error TS2307: Cannot find module 'firebase/app'.
node_modules/angularfire2/firebase.app.module.d.ts(3,27): error TS2307: Cannot find module 'firebase/app'.

**Comment by harikrishna266** [comment]
Do you have this issue on the latest pull?

**Comment by hooh88** [comment]
Yes

**Comment by harikrishna266** [comment]
Is this issue still there?

**Comment by kamleshkatpara** [comment]
@harikrishna266  Yes, even I faced the same issue after cloning your repo, I tried npm install and then ng server gives that error

**Comment by harikrishna266** [comment]
can you try this.

**Comment by kamleshkatpara** [comment]
@harikrishna266  try what ?

**Comment by harikrishna266** [comment]
@kamleshkatpara sorry did not realise that the copy paste did not work
https://stackoverflow.com/questions/47920838/typescript-error-cannot-find-module-firebase-app

**Comment by kamleshkatpara** [comment]
@harikrishna266  Nope, still not working, can you try to clone this repo on your end and check whether it works ?

**Comment by kamleshkatpara** [comment]
![capture](https://user-images.githubusercontent.com/16983847/44577641-7c508080-a746-11e8-8c51-951d1437f5be.PNG)

**Comment by kamleshkatpara** [comment]
```

**Comment by yeshwanthmn** [comment]
Can I add bootstrap in this theme

**Comment by Xonshiz** [comment]
Why was this closed? I've cloned this repo and I'm still facing this issue. Unfortunately, that StackoverFlow link doesn't help either.
