### ISSUE TITLE
Can Not Generate New Component 

### ISSUE THREAD

**Issue by rahulsetia25** [codetok/cdk-admin#16]
Can Not Generate New Component  Using this Command : ng generate component component-name

Shows : Could not find an NgModule. Use the skip-import option to skip importing in NgModule.

**Comment by Iznogood1** [comment]
+

**Comment by harikrishna266** [comment]
can you pull the code and try it again

**Comment by rahulsetia25** [comment]
Problem Is Still same

**Comment by harikrishna266** [comment]
if you go to this link, There is way to fix the issue. Can you try this and let me know if this works. 
https://github.com/angular/angular-cli/issues/10684#issuecomment-399038618
