### ISSUE TITLE
bootstrap cdn links

### ISSUE THREAD

**Issue by manigujjula** [codetok/cdk-admin#19]
When i give bootstrap cdn links , Dashboard width reduced .How can i give full-width.
![capturedddd](https://user-images.githubusercontent.com/26201650/45403920-6ca7c600-b67a-11e8-8352-0629685ab6b4.PNG)

**Comment by harikrishna266** [comment]
there could be conflicting classes name.Try to figure out which class getting over written by bootstrap.
Can you let me know why you need bootstrap?

**Comment by manigujjula** [comment]
> there could be conflicting classes name.Try to figure out which class getting over written by bootstrap.
> Can you let me know why you need bootstrap?

.Thanks for the reply ,Here i'm using bootstrap data tables.Anyway i solved the isssue
