### ISSUE TITLE
Is there any plans to support angular 6 and material 6?

### ISSUE THREAD

**Issue by ElderJames** [codetok/cdk-admin#5]
Hey there,
I am glad to discover this awesome project! Ant right now, angular 6 and material 6 has been released,so do you have any plans to support them?

**Comment by HackPoint** [comment]
@ElderJames say have you tried to export MaterialWidgets how to do it?

**Comment by harikrishna266** [comment]
i would love to upgrade everything with this theme. But right now i'm busy with other things, so i'm not sure when i will be able to upgrade things. Sorry!

**Comment by Adiel-Sharabi** [comment]
Hi, We've updated the project to Angular 6.
