### ISSUE TITLE
Menu is not showing

### ISSUE THREAD

**Issue by knandhucse** [codetok/cdk-admin#9]
Application side menu is showing icons alone when we click the hamburger menu at the top in your live demo. But when I download and run the project, the overall menu is hiding. 
![cdkadminmenu](https://user-images.githubusercontent.com/41463154/42992554-7ba3e392-8c26-11e8-8d0d-8ebfb340e144.png)

**Comment by harikrishna266** [comment]
i could not get that issue on my browser. 
if you need to get the small menu you can uncomment the code in  here
https://github.com/codetok/cdk-admin/blob/master/src/app/auth/auth.component.html

**Comment by knandhucse** [comment]
Wow! Thanks, Hari. But I have the following issue when I uncomment that code.

![image](https://user-images.githubusercontent.com/41463154/42996081-1f378136-8c30-11e8-94ed-3d896c6592ec.png)

**Comment by harikrishna266** [comment]
fixed that, please pull and check.

**Comment by knandhucse** [comment]
Hi Hari,
Thank you for your quick responses. Now the above issue has been fixed and again I have one more issue in the menu, please check the screenshot below. The submenus are hiding.

![image](https://user-images.githubusercontent.com/41463154/43006868-6a76aaf4-8c54-11e8-80f8-bd715016b8c3.png)
